application: timer-1067
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /api.*
  script: api.app

- url: /timer
  script: main.app
  secure: always
  login: required

- url: .*
  script: main.app
  secure: always
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
